DROP TABLE IF EXISTS maps CASCADE;
CREATE TABLE maps (
  id SERIAL PRIMARY KEY ON DELETE CASCADE NOT NULL,
  user_id INTEGER ON DELETE CASCADE FOREIGN KEY NOT NULL,
  zoom INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL
);
